####################################### Services
services:
  service-prometheus:
    image: ahmettoguz/prometheus:v3.2.1
    container_name: container-prometheus
    volumes:
      - volume-prometheus:/prometheus
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - network-monitor
    restart: ${RESTART_POLICY}
    # ports:
    #   - 9090:9090

####################################### Networks
networks:
  network-monitor:
    external: true

####################################### Volumes
volumes:
  volume-prometheus:
    name: volume-prometheus
