global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets: ["service-cadvisor:8080"]

  - job_name: "traefik"
    static_configs:
      - targets: ["service-traefik:8082"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["service-node-exporter:9100"]
